apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotestcicd
  name: gotestcicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotestcicd
  template:
    metadata:
      labels:
        app: gotestcicd
    spec:
      containers:
      - image: 10.34.100.113/skyatlas/devops-go-sample:latest
        imagePullPolicy: Always
        name: gotestcicd

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gotestcicd
  name: gotestcicd
spec:
  ports:
  - nodePort: 32224
    port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: gotestcicd
  type: NodePort
